### PR TITLE
Remove Spark usage for Kafka functionality

### PR DESCRIPTION
**Pull request by gemelen**
Idea is to remove Spark's KafkaCluster usage completely and use Kafka's own API.
Changeset brings usage of AdminClient and KafkaConsumer methods to obtain consumer group's committed offsets and leading offsets for particular consumer group.
Caching mechanism is used between subsequent calls of Kafka APIs for performance reasons.
Also minor changes are made in Kafka section of configuration.

### CODE REVIEW

**Comment by gemelen** [comment]
Reported metrics are a bit wrong, won't merge PR till the fix arrival.

**Comment by alexey-lipodat** [comment]
Looks cool :)

**Comment by gemelen** [comment]
Lag is still wrong and also interference with cluster needs to be investigated.

**Comment by gemelen** [comment]
Fix of the logic in courtesy of @MariiaRa 
Tested, reported metrics are fine and correlates with previous approach. No interference on Kafka brokers was observed during test run.

**Pull request merged**
